export const citiesOptions = [
  { title: "Adjud", value: "adjud" },
  { title: "Agnita", value: "agnita" },
  { title: "Aiud", value: "aiud" },
  { title: "Alba Iulia", value: "alba-iulia" },
  { title: "Alexandria", value: "alexandria" },
  { title: "Aleșd", value: "alesd" },
  { title: "Amara", value: "amara" },
  { title: "Anina", value: "anina" },
  { title: "Aninoasa", value: "aninoasa" },
  { title: "Arad", value: "arad" },
  { title: "Ardud", value: "ardud" },
  { title: "Avrig", value: "avrig" },
  { title: "Azuga", value: "azuga" },
  { title: "Babadag", value: "babadag" },
  { title: "Bacău", value: "bacau" },
  { title: "Baia Mare", value: "baia-mare" },
  { title: "Baia de Aramă", value: "baia-de-arama" },
  { title: "Balș", value: "bals" },
  { title: "Baraolt", value: "baraolt" },
  { title: "Bechet", value: "bechet" },
  { title: "Beclean", value: "beclean" },
  { title: "Beiuș", value: "beius" },
  { title: "Berbești", value: "berbesti" },
  { title: "Berești", value: "beresti" },
  { title: "Bicaz", value: "bicaz" },
  { title: "Bistrița", value: "bistrita" },
  { title: "Blaj", value: "blaj" },
  { title: "Bocșa", value: "bocsa" },
  { title: "Boldești-Scăeni", value: "boldesti-scaeni" },
  { title: "Bolintin-Vale", value: "bolintin-vale" },
  { title: "Borsec", value: "borsec" },
  { title: "Borșa", value: "borsa" },
  { title: "Botoșani", value: "botosani" },
  { title: "Brad", value: "brad" },
  { title: "Bragadiru", value: "bragadiru" },
  { title: "Brașov", value: "brasov" },
  { title: "Breaza", value: "breaza" },
  { title: "Brezoi", value: "brezoi" },
  { title: "Brăila", value: "braila" },
  { title: "București", value: "bucuresti" },
  { title: "Budești", value: "budesti" },
  { title: "Buftea", value: "buftea" },
  { title: "Buhuşi", value: "buhusi" },
  { title: "Bumbești-Jiu", value: "bumbesti-jiu" },
  { title: "Buziaș", value: "buzias" },
  { title: "Buzău", value: "buzau" },
  { title: "Bușteni", value: "busteni" },
  { title: "Bârlad", value: "barlad" },
  { title: "Băbeni", value: "babeni" },
  { title: "Băicoi", value: "baicoi" },
  { title: "Băile Govora", value: "baile-govora" },
  { title: "Băile Olănești", value: "baile-olanesti" },
  { title: "Băile Tușnad", value: "baile-tusnad" },
  { title: "Băilești", value: "bailesti" },
  { title: "Bălan", value: "balan" },
  { title: "Bălcești", value: "balcesti" },
  { title: "Calafat", value: "calafat" },
  { title: "Caracal", value: "caracal" },
  { title: "Caransebeș", value: "caransebes" },
  { title: "Carei", value: "carei" },
  { title: "Cavnic", value: "cavnic" },
  { title: "Cehu Silvaniei", value: "cehu-silvaniei" },
  { title: "Cernavodă", value: "cernavoda" },
  { title: "Chitila", value: "chitila" },
  { title: "Ciacova", value: "ciacova" },
  { title: "Cisnădie", value: "cisnadie" },
  { title: "Cluj-Napoca", value: "cluj-napoca" },
  { title: "Codlea", value: "codlea" },
  { title: "Comarnic", value: "comarnic" },
  { title: "Comănești", value: "comanesti" },
  { title: "Constanța", value: "constanta" },
  { title: "Copșa Mică", value: "copsa-mica" },
  { title: "Corabia", value: "corabia" },
  { title: "Costești", value: "costesti" },
  { title: "Covasna", value: "covasna" },
  { title: "Craiova", value: "craiova" },
  { title: "Cristuru Secuiesc", value: "cristuru-secuiesc" },
  { title: "Cugir", value: "cugir" },
  { title: "Curtea de Argeș", value: "curtea-de-arges" },
  { title: "Curtici", value: "curtici" },
  { title: "Câmpia Turzii", value: "campia-turzii" },
  { title: "Câmpulung", value: "campulung" },
  { title: "Câmpulung Moldovenesc", value: "campulung-moldovenesc" },
  { title: "Călan", value: "calan" },
  { title: "Călimănești", value: "calimanesti" },
  { title: "Călărași", value: "calarasi" },
  { title: "Darabani", value: "darabani" },
  { title: "Dej", value: "dej" },
  { title: "Deta", value: "deta" },
  { title: "Deva", value: "deva" },
  { title: "Dorohoi", value: "dorohoi" },
  { title: "Dragomirești", value: "dragomiresti" },
  { title: "Drobeta-Turnu Severin", value: "drobeta-turnu-severin" },
  { title: "Drăgănești-Olt", value: "draganesti-olt" },
  { title: "Drăgășani", value: "dragasani" },
  { title: "Dumbrăveni", value: "dumbraveni" },
  { title: "Dărmănești", value: "darmanesti" },
  { title: "Eforie", value: "eforie" },
  { title: "Fetești", value: "fetesti" },
  { title: "Fieni", value: "fieni" },
  { title: "Filiași", value: "filiasi" },
  { title: "Focșani", value: "focsani" },
  { title: "Fundulea", value: "fundulea" },
  { title: "Făcăeni", value: "facaeni" },
  { title: "Făget", value: "faget" },
  { title: "Făgăraș", value: "fagaras" },
  { title: "Fălticeni", value: "falticeni" },
  { title: "Făurei", value: "faurei" },
  { title: "Galați", value: "galati" },
  { title: "Gheorgheni", value: "gheorgheni" },
  { title: "Gherla", value: "gherla" },
  { title: "Giurgiu", value: "giurgiu" },
  { title: "Gura Humorului", value: "gura-humorului" },
  { title: "Găești", value: "gaesti" },
  { title: "Gătaia", value: "gataia" },
  { title: "Hațeg", value: "hateg" },
  { title: "Horezu", value: "horezu" },
  { title: "Huedin", value: "huedin" },
  { title: "Hunedoara", value: "hunedoara" },
  { title: "Huși", value: "husi" },
  { title: "Hârlău", value: "harlau" },
  { title: "Ianca", value: "ianca" },
  { title: "Iași", value: "iasi" },
  { title: "Iernut", value: "iernut" },
  { title: "Ineu", value: "ineu" },
  { title: "Isaccea", value: "isaccea" },
  { title: "Jibou", value: "jibou" },
  { title: "Jimbolia", value: "jimbolia" },
  { title: "Lehliu-Gară", value: "lehliu-gara" },
  { title: "Lipova", value: "lipova" },
  { title: "Livada", value: "livada" },
  { title: "Luduș", value: "ludus" },
  { title: "Lugoj", value: "lugoj" },
  { title: "Lupeni", value: "lupeni" },
  { title: "Mangalia", value: "mangalia" },
  { title: "Marghita", value: "marghita" },
  { title: "Medgidia", value: "medgidia" },
  { title: "Mediaș", value: "medias" },
  { title: "Miercurea Ciuc", value: "miercurea-ciuc" },
  { title: "Miercurea Sibiului", value: "miercurea-sibiului" },
  { title: "Mihăilești", value: "mihailesti" },
  { title: "Mioveni", value: "mioveni" },
  { title: "Mizil", value: "mizil" },
  { title: "Moinești", value: "moinesti" },
  { title: "Moldova Nouă", value: "moldova-noua" },
  { title: "Moreni", value: "moreni" },
  { title: "Motru", value: "motru" },
  { title: "Murfatlar", value: "murfatlar" },
  { title: "Murgeni", value: "murgeni" },
  { title: "Măcin", value: "macin" },
  { title: "Măgurele", value: "magurele" },
  { title: "Mărășești", value: "marasesti" },
  { title: "Negrești", value: "negresti" },
  { title: "Negrești-Oaș", value: "negresti-oas" },
  { title: "Negru Vodă", value: "negru voda" },
  { title: "Nehoiu", value: "nehoiu" },
  { title: "Novaci", value: "novaci" },
  { title: "Nădlac", value: "nadlac" },
  { title: "Năsăud", value: "nasaud" },
  { title: "Năvodari", value: "navodari" },
  { title: "Ocna Mureș", value: "ocna-mures" },
  { title: "Ocna Sibiului", value: "ocna-sibiului" },
  { title: "Ocnele Mari", value: "ocnele mari" },
  { title: "Odobești", value: "odobesti" },
  { title: "Odorheiu Secuiesc", value: "odorheiu-secuiesc" },
  { title: "Oltenița", value: "oltenita" },
  { title: "Onești", value: "onesti" },
  { title: "Oradea", value: "oradea" },
  { title: "Oravița", value: "oravita" },
  { title: "Orăștie", value: "orastie" },
  { title: "Orșova", value: "orsova" },
  { title: "Otopeni", value: "otopeni" },
  { title: "Ovidiu", value: "ovidiu" },
  { title: "Oțelu Roșu", value: "otelu-rosu" },
  { title: "Panciu", value: "panciu" },
  { title: "Pantelimon", value: "pantelimon" },
  { title: "Pașcani", value: "pascani" },
  { title: "Pecica", value: "pecica" },
  { title: "Petrila", value: "petrila" },
  { title: "Petroșani", value: "petrosani" },
  { title: "Piatra Neamț", value: "piatra-neamt" },
  { title: "Piatra-Olt", value: "piatra-olt" },
  { title: "Pitești", value: "pitesti" },
  { title: "Ploiești", value: "ploiesti" },
  { title: "Plopeni", value: "plopeni" },
  { title: "Podu Iloaiei", value: "podu-iloaiei" },
  { title: "Pogoanele", value: "pogoanele" },
  { title: "Popești-Leordeni", value: "popesti-leordeni" },
  { title: "Potcoava", value: "potcoava" },
  { title: "Predeal", value: "predeal" },
  { title: "Pucioasa", value: "pucioasa" },
  { title: "Pâncota", value: "pancota" },
  { title: "Pătârlagele", value: "patarlagele" },
  { title: "Recaș", value: "recas" },
  { title: "Reghin", value: "reghin" },
  { title: "Reșița", value: "resita" },
  { title: "Roman", value: "roman" },
  { title: "Rovinari", value: "rovinari" },
  { title: "Roșiorii de Vede", value: "rosiorii-de-vede" },
  { title: "Rupea", value: "rupea" },
  { title: "Râmnicu Sărat", value: "ramnicu-sarat" },
  { title: "Râmnicu Vâlcea", value: "ramnicu-valcea" },
  { title: "Râșnov", value: "rasnov" },
  { title: "Răcari", value: "racari" },
  { title: "Rădăuți", value: "radauti" },
  { title: "Salonta", value: "salonta" },
  { title: "Satu Mare", value: "satu-mare" },
  { title: "Scornicești", value: "scornicesti" },
  { title: "Sebeș", value: "sebes" },
  { title: "Segarcea", value: "segarcea" },
  { title: "Seini", value: "seini" },
  { title: "Sfântu Gheorghe", value: "sfantu-gheorghe" },
  { title: "Sibiu", value: "sibiu" },
  { title: "Sighetu Marmației", value: "sighetu-marmatiei" },
  { title: "Sighișoara", value: "sighisoara" },
  { title: "Simeria", value: "simeria" },
  { title: "Sinaia", value: "sinaia" },
  { title: "Siret", value: "siret" },
  { title: "Slatina", value: "slatina" },
  { title: "Slobozia", value: "slobozia" },
  { title: "Slănic", value: "slanic" },
  { title: "Slănic Moldova", value: "slanic-moldova" },
  { title: "Solca", value: "solca" },
  { title: "Sovata", value: "sovata" },
  { title: "Strehaia", value: "strehaia" },
  { title: "Suceava", value: "suceava" },
  { title: "Sulina", value: "sulina" },
  { title: "Sângeorz-Băi", value: "sangeorz-bai" },
  { title: "Sânnicolau Mare", value: "sannicolau-mare" },
  { title: "Sântana", value: "santana" },
  { title: "Săcele", value: "sacele" },
  { title: "Săcueni", value: "sacueni" },
  { title: "Săliștea de Sus", value: "salistea-de-sus" },
  { title: "Sărmașu", value: "sarmasu" },
  { title: "Săveni", value: "saveni" },
  { title: "Techirghiol", value: "techirghiol" },
  { title: "Timișoara", value: "timisoara" },
  { title: "Tismana", value: "tismana" },
  { title: "Titu", value: "titu" },
  { title: "Toplița", value: "toplita" },
  { title: "Topoloveni", value: "topoloveni" },
  { title: "Tulcea", value: "tulcea" },
  { title: "Turceni", value: "turceni" },
  { title: "Turda", value: "turda" },
  { title: "Turnu Măgurele", value: "turnu-magurele" },
  { title: "Târgoviște", value: "targoviste" },
  { title: "Târgu Bujor", value: "targu-bujor" },
  { title: "Târgu Cărbunești", value: "targu-carbunesti" },
  { title: "Târgu Frumos", value: "targu-frumos" },
  { title: "Târgu Jiu", value: "targu-jiu" },
  { title: "Târgu Lăpuș", value: "targu-lapus" },
  { title: "Târgu Mureș", value: "targu-mures" },
  { title: "Târgu Neamț", value: "targu-neamt" },
  { title: "Târgu Ocna", value: "targu-ocna" },
  { title: "Târgu Secuiesc", value: "targu-secuiesc" },
  { title: "Târnăveni", value: "tarnaveni" },
  { title: "Tălmaciu", value: "talmaciu" },
  { title: "Tășnad", value: "tasnad" },
  { title: "Ulmeni", value: "ulmeni" },
  { title: "Uricani", value: "uricani" },
  { title: "Urlați", value: "urlati" },
  { title: "Urziceni", value: "urziceni" },
  { title: "Valea lui Mihai", value: "valea-lui-mihai" },
  { title: "Vaslui", value: "vaslui" },
  { title: "Vatra Dornei", value: "vatra-dornei" },
  { title: "Victoria", value: "victoria" },
  { title: "Videle", value: "videle" },
  { title: "Vișeu de Sus", value: "viseu-de-sus" },
  { title: "Vlăhița", value: "vlahita" },
  { title: "Voluntari", value: "voluntari" },
  { title: "Vulcan", value: "vulcan" },
  { title: "Vânju Mare", value: "vanju-mare" },
  { title: "Vălenii de Munte", value: "valenii-de-munte" },
  { title: "Zalău", value: "zalau" },
  { title: "Zimnicea", value: "zimnicea" },
  { title: "Zlatna", value: "zlatna" },
  { title: "Zărnești", value: "zarnesti" },
  { title: "Șimleu Silvaniei", value: "simleu-silvaniei" },
  { title: "Ștefănești", value: "stefanesti" },
  { title: "Ștei", value: "stei" },
  { title: "Țicleni", value: "ticleni" },
  { title: "Țăndărei", value: "tandarei" },
];